version: "3"

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - 127.0.0.1:${MONGODB_PORT:-27017}:${MONGODB_PORT:-27017}
    volumes:
      - ${MONGODB_PATH:-./mongodb}:/data/db
    networks:
      - cgptg-back-tier

  cgptgbot:
    image: cgptg-tgbot
    container_name: cgptg-tgbot
    command: python3 bot/bot.py
    restart: always
    build:
      context: "."
      dockerfile: Dockerfile
    depends_on:
      - mongo
    volumes:
      - ./:/code
    networks:
      - cgptg-back-tier
      - cgptg-front-tier

  cgptg_mongoe:
    container_name: cgptg-mongoe
    image: mongo-express:latest
    restart: always
    ports:
      - 127.0.0.1:${MONGO_EXPRESS_PORT:-8081}:${MONGO_EXPRESS_PORT:-8081}
    environment:
      - ME_CONFIG_MONGODB_SERVER=${MONGODB_HOSTNAME:-mongo}
      - ME_CONFIG_MONGODB_PORT=${MONGODB_PORT:-27017}
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=chatgpt_telegram_bot
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_USERNAME:-username}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PASSWORD:-password}
    depends_on:
      - mongo
    networks:
      - cgptg-back-tier
      - cgptg-front-tier

networks:
  cgptg-front-tier:
    name: cgptg-front-tier
  cgptg-back-tier:
    name: cgptg-back-tier